### ISSUE TITLE
Time-based queue flushing is broken after socket is closed

### ISSUE THREAD

**Issue by mpareja** [uber/node-statsd-client#31]
Here is a failing test case: https://github.com/mpareja/node-statsd-client/blob/queue-flush/test/socket.js#L214.

The [internal tear-down of the socket performed by EphemeralSocket](https://github.com/uber/node-statsd-client/blob/master/lib/EphemeralSocket.js#L70) calls the public `EphemeralSocket.close` method. This results in the [destruction of the PacketQueue instance](https://github.com/uber/node-statsd-client/blob/master/lib/EphemeralSocket.js#L78) which [permanently clears the time-based queue flushing](https://github.com/uber/node-statsd-client/blob/master/lib/packet-queue.js#L64). Time based queue flushing is never re-enabled.

**Comment by Raynos** [comment]
That sounds like a bug to me.

Would you like to open a PR with a fix ?

**Comment by mpareja** [comment]
@Raynos Yeah, I'll submit a PR.

**Comment by mpareja** [comment]
FYI I noticed the DNS resolver would also stop responding with DNS query results after socket timeout. That's been fixed by my PR as well.

Is there anything else that needs to happen for a new version of this package to be published?

**Comment by niclic** [comment]
+1

**Comment by Raynos** [comment]
Merged & published 1.5.0

**Comment by mpareja** [comment]
Sweet, thanks @Raynos. :+1:
